### PR TITLE
Allow captures and replacements

### PR DESCRIPTION
**Pull request by hexylena**
I am absolutely not sure this works, do we have a staging environment?

### CODE REVIEW

**Comment by natefoo** [comment]
> do we have a staging environment?

No unfortunately, although we can roll back the rule if anything breaks severely in an unfixable manner.

Re: skipping tests, we could probably add a dict form of test cases to have a `src` and `dest` so that you can actually have a test case or two for stuff with backreferences.

**Comment by hexylena** [comment]
Yeah fair enough. This is priority: low, so, no dramas.

**Review by natefoo — APPROVED** [review]
:shipit:

**Comment by hexylena** [comment]
:shipit: zwj past-tense-emoji

**Pull request merged**
